server:
  port: 9394
spring:
 application:
  name: ms-clientes
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:9395/eureka
  instance:
    hostname: localhost