server:
  port: 9088
spring:
 application:
  name: gateway
 cloud:
  config:
   enabled: true
  gateway:
   discovery:
        locator:
          enabled: true
   routes:
   - id: ms-clientes #definido por mi solo es el nombre que se le quiera colocar
     uri: lb://ms-clientes # application name del ms : nombre del micro
     predicates: 
      - Path=/clientes/** #path definido en el "RestController "Controller (/**) considera todo lo posterior a ese path
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost      
      
      
